name: 'AI Code Review'
description: 'AI-powered code review using Claude or Codex, triggered by @Claude or @Codex comments'
author: 'Your Name'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: false
  openai_api_key:
    description: 'OpenAI API key for Codex/GPT'
    required: false
  default_provider:
    description: 'Default AI provider (claude or codex)'
    required: false
    default: 'claude'
  claude_model:
    description: 'Claude model to use'
    required: false
    default: 'claude-sonnet-4-20250514'
  codex_model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4o'
  platform:
    description: 'Git platform type (forgejo, github, gitlab, etc.)'
    required: false
    default: 'forgejo'
  platform_token:
    description: 'Git platform API token with repo permissions'
    required: false
  platform_url:
    description: 'Git platform instance URL (e.g. https://codeberg.org)'
    required: false
  forgejo_token:
    description: 'Deprecated: use platform_token instead. Forgejo API token with repo permissions.'
    required: false
  forgejo_url:
    description: 'Deprecated: use platform_url instead. Forgejo instance URL.'
    required: false
  context_files:
    description: 'Comma-separated list of file paths (relative to repo root) to include as context for the AI reviewer (e.g. ARCHITECTURE.md,REVIEW_HINTS.md)'
    required: false
    default: ''
  jira_project_key:
    description: 'Jira project key prefix to match in PR titles/branch names (e.g., ECOM). If omitted, any UPPERCASE-123 pattern is matched.'
    required: false
  jira_url:
    description: 'Jira instance base URL (e.g., https://yourteam.atlassian.net)'
    required: false
  jira_email:
    description: 'Jira account email for API authentication'
    required: false
  jira_api_token:
    description: 'Jira API token'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
