name: 'AI Code Review'
description: 'AI-powered code review using Claude or Codex, triggered by @Claude or @Codex comments'
author: 'Your Name'

inputs:
  anthropic_api_key:
    description: 'Anthropic API key for Claude'
    required: false
  openai_api_key:
    description: 'OpenAI API key for Codex/GPT'
    required: false
  default_provider:
    description: 'Default AI provider (claude or codex)'
    required: false
    default: 'claude'
  claude_model:
    description: 'Claude model to use'
    required: false
    default: 'claude-sonnet-4-20250514'
  codex_model:
    description: 'OpenAI model to use'
    required: false
    default: 'gpt-4o'
  platform:
    description: 'Git platform type (forgejo, github, gitlab, etc.)'
    required: false
    default: 'forgejo'
  platform_token:
    description: 'Git platform API token with repo permissions'
    required: false
  platform_url:
    description: 'Git platform instance URL (e.g. https://codeberg.org)'
    required: false
  forgejo_token:
    description: 'Deprecated: use platform_token instead. Forgejo API token with repo permissions.'
    required: false
  forgejo_url:
    description: 'Deprecated: use platform_url instead. Forgejo instance URL.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
